### ISSUE TITLE
NPV not working

### ISSUE THREAD

**Issue by Stanzarectah** [essamjoubori/finance.js#20]
I tried your example:

finance.NPV(10, -500000, 200000, 300000, 200000);

I get 80015.03

But when I try it in Excel: =NPV(0.1, -500000, 200000, 300000, 200000)

I get 72740.93

Am I missing something here?

I need to replicate the NPV functionality in Jscript but I can't do this when I am getting 2 different results.

Any help would be appreciated.

**Comment by essamjoubori** [comment]
Hi @Stanzarectah 

The Excel NPV function calculates the present value of a series of cash flows and not net present value. In order to calculate NPV in Excel with the NPV function, you will need to exclude the initial cash outflow and add it to the equation later. In other words, =NPV(0.1, 200000, 300000, 200000) + (-500000)

Hope that makes sense.
